<section class="register">
<h2>Регистрация</h2>
<?php if ($this->error): ?>
<p class="error">
Форма заполнена с ошибками. Пожалуйста, заполните все поля корректно. Спасибо!
</p>
<?php endif; ?>
<?php   //Следующий блок предназначен для генерации HTML-тега <form>
	//присвоенного представлению в контроллере
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url(NULL,
	array('controller' => 'Register', 'action' => 'process')));
	$form->setAttribute('method', 'post');
	echo $this->form()->openTag($form);
?>
<?php	//Следующий раздел служит для генерации отдельных элементов формы, соответствующих полям 
	//Name, Email, Password, Comfirm Password и Submit
?>
<dl class="zend_form">
<dt><?php print $this->formLabel($form->get('name')); ?></dt>
<dd><?php
	print $this->formElement($form->get('name')); 
	print $this->formElementErrors($form->get('name'));
?></dd>
<dt><?php print $this->formLabel($form->get('email')); ?></dt>
<dd><?php
	print $this->formElement($form->get('email'));
	print $this->formElementErrors($form->get('email'));
?></dd>
<dt><?php print $this->formLabel($form->get('password')); ?></dt>
<dd><?php 
	print $this->formElement($form->get('password'));
	print $this->formElementErrors($form->get('password')); 
?></dd>
<dt><?php print $this->formLabel($form->get('confirm_password')); ?></dt>
<dd><?php
	print $this->formElement($form->get('confirm_password'));
	print $this->formElementErrors($form->get('confirm_password'));
?></dd>
<dd><?php 
	print $this->formElement($form->get('submit'));
	print $this->formElementErrors($form->get('submit'));
?></dd>
</dl>
<?php print $this->form()->closeTag(); ?>
</section>
